### PR TITLE
Add Random module to Kconfig

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
Adds the random (PRNG) modules to Kconfig. Plus other extra modules needed for the test application.

### Testing procedure
Test with tests/rng.

### Issues/PRs references
None.

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
Works with nrf52840dk and SHA256PRNG, thanks!

**Comment by PeterKietzmann** [comment]
I would also like to run the fortuna generator but it does not compile. Can you have a look at that too?

**Comment by leandrolanzieri** [comment]
> I would also like to run the fortuna generator but it does not compile. Can you have a look at that too?

I'll look into it

**Comment by leandrolanzieri** [comment]
Please check again now

**Comment by PeterKietzmann** [comment]
Works as expected now. Thanks!

**Pull request merged**
